### ISSUE TITLE
How do you actually use this package?

### ISSUE THREAD

**Issue by limianwang** [envygeeks/atom-comment-headers#4]
Hello,

I just download this package, and when I attempt to do:  `comment-headers:insert` Nothing happens. Also is there the ability of setting custom templates and where?

A bit more documentation would be awesome!

Thanks!

**Comment by envygeeks** [comment]
Unless your language is supported nothing will happen so what language are you using?  As for custom templates, there is no need for it, it's a comment header, what kind of template would you want?

**Comment by limianwang** [comment]
Ah I see. My bad. I was thinking I was using it for `node`/`javascript` but in fact it was for `Go` maybe that's why. I just double checked and `Go` wasn't part of the list. 

For some reason I thought I would be able to use this package for something more like the `FileHeader` for Sublime Text, which would be neat...

**Comment by envygeeks** [comment]
I do have plans to eventually build something like FileHeader but for the time being I do not have time to build that kind of plugin because I am wrapped up with other projects.

**Comment by envygeeks** [comment]
I will however add Go to the list.
