### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by dferber90** [envygeeks/atom-comment-headers#6]
Awesome package!

Could you please add the "Babel ES6 Javascript" grammar which behaves just like regular Javascript?
It stems from [language-babel](https://atom.io/packages/language-babel).

**Comment by envygeeks** [comment]
Fixed via #7

**Comment by dferber90** [comment]
#7 is unfortunately not the grammar I was looking for :)

**Comment by envygeeks** [comment]
Bah, I got the ticket number wrong but I added Babel for you.

**Comment by envygeeks** [comment]
See: https://github.com/envygeeks/atom-comment-headers/commit/8b61f22d746b3f2c085efab232ee245b189b9222

**Comment by dferber90** [comment]
Okay, I also sent a PR doing the same in #8 :) Guess that can be closed then. Thank you :+1:
